@REM pytest -m user365 -s -v --capture=sys --html=Reports\B2BTestReport.html --self-contained-html testcases\B2Btest.py
@REM pytest -m abdexch -s -v --capture=sys --html=Reports\abdexchTestReport.html --self-contained-html TestCases\
@REM pytest -m aura25 -s -v --capture=sys --html=Reports\aura25TestReport.html --self-contained-html TestCases\
@REM pytest -m badabet -s -v --capture=sys --html=Reports\badabetTestReport.html --self-contained-html TestCases\
@REM pytest -m infinity -s -v --capture=sys --html=Reports\infinityTestReport.html --self-contained-html TestCases\
@REM pytest -m user365 -s -v --capture=sys --html=Reports\user365TestReport.html --self-contained-html TestCases\
@REM pytest -m only333 -s -v --capture=sys --html=Reports\only333TestReport.html --self-contained-html TestCases\
@REM pytest -m pk7 -s -v --capture=sys --html=Reports\pk7TestReport.html --self-contained-html TestCases\
@REM pytest -m gamex -s -v --capture=sys --html=Reports\gamexTestReport.html --self-contained-html TestCases\
@REM pytest -m aura26 -s -v --capture=sys --html=Reports\aura26TestReport.html --self-contained-html TestCases\
@REM pytest -m xtra999 -s -v --capture=sys --html=Reports\xtra999TestReport.html --self-contained-html TestCases\
@REM pytest -m run567 -s -v --capture=sys --html=Reports\run567TestReport.html --self-contained-html TestCases\
@REM pytest -m thalaiva -s -v --capture=sys --html=Reports\thalaivaTestReport.html --self-contained-html TestCases\
@REM pytest -m empire -s -v --capture=sys --html=Reports\empireTestReport.html --self-contained-html TestCases\
@REM pytest -m hattrick -s -v --capture=sys --html=Reports\hattrickTestReport.html --self-contained-html TestCases\